/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Throws8008s
 */
public class HomePage extends javax.swing.JFrame {

    
    java.sql.Connection con=Lost_n_Found.connectdb();
    PreparedStatement ps=null;
    ResultSet rs=null;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Lost_n_Found.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_field = new javax.swing.JLabel();
        password_field = new javax.swing.JLabel();
        Btnlogin = new javax.swing.JButton();
        BtnSignUp = new javax.swing.JButton();
        BtnQuit = new javax.swing.JButton();
        id_passport = new javax.swing.JTextField();
        show_password = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();
        welcome_logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_field.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        email_field.setForeground(new java.awt.Color(0, 0, 0));
        email_field.setText("ID / Passport : ");
        getContentPane().add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 30));

        password_field.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        password_field.setForeground(new java.awt.Color(0, 0, 0));
        password_field.setText("Password :");
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        Btnlogin.setForeground(new java.awt.Color(0, 255, 0));
        Btnlogin.setText("Log in");
        Btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnloginMouseExited(evt);
            }
        });
        Btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnloginActionPerformed(evt);
            }
        });
        getContentPane().add(Btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        BtnSignUp.setForeground(new java.awt.Color(0, 102, 255));
        BtnSignUp.setText("Register");
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        BtnQuit.setForeground(new java.awt.Color(255, 0, 0));
        BtnQuit.setText("Quit");
        BtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        id_passport.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        id_passport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id_passportFocusGained(evt);
            }
        });
        getContentPane().add(id_passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, 30));

        show_password.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        show_password.setForeground(new java.awt.Color(0, 0, 0));
        show_password.setText("Show password");
        show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        passwordField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, 30));

        welcome_logo.setFont(new java.awt.Font("Bradley Hand ITC", 3, 48)); // NOI18N
        welcome_logo.setForeground(new java.awt.Color(0, 0, 0));
        welcome_logo.setText("Welcome");
        getContentPane().add(welcome_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 50));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\fab29ab453b713c7bf599c995cdf96fa.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnloginActionPerformed
        // TODO add your handling code here:
         if(id_passport.getText().trim().isEmpty() && passwordField.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "ID/Passport number or Password is Incorrect !!!");
       }
       else if(id_passport.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "ID/Passport number Field is Empty !!");
       }
        else if(passwordField.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Password Field is Empty !!");
       }
       try{
           String sql="SELECT * FROM USER_DATA WHERE ID=? AND PASSWORD=?";
        ps=con.prepareStatement (sql);   
        ps.setString(1,id_passport.getText());
        ps.setString(1,passwordField.getText());
        rs=ps.executeQuery();
        if(rs.next()){
            //JOptionPane.showMessageDialog(null, "Login Successfully...!");
            this.setVisible(true);
            new Navigation().setVisible(true); // Main Form to show after the Sign Up Form..
            dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Login Failed  /nTRY AGAIN...!!");
            dispose();
            passwordField.setText("");
            id_passport.setText("");
        }
       }
       catch(SQLException ex)
               {
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_BtnloginActionPerformed

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new NewUser().setVisible(true); // Main Form to show after the Sign Up Form..
        this.dispose();
    }//GEN-LAST:event_BtnSignUpActionPerformed

    private void BtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnQuitActionPerformed

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        // TODO add your handling code here:
        // Masking your password:
        if (show_password.isSelected()) {
      passwordField.setEchoChar((char)0); //password = JPasswordField
   } else {
      passwordField.setEchoChar('*');}
    }//GEN-LAST:event_show_passwordActionPerformed

    private void id_passportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_passportFocusGained
        // Clear the Text Field on focus if the text is "Username"
        if(id_passport.getText().trim().toLowerCase().equals("username"))
        {
            id_passport.setText("");
            id_passport.setForeground(Color.black);
        }
    }//GEN-LAST:event_id_passportFocusGained

    private void BtnloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnloginMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnloginMouseEntered

    private void BtnloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnloginMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnloginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnQuit;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JButton Btnlogin;
    private javax.swing.JLabel background;
    private javax.swing.JLabel email_field;
    private javax.swing.JTextField id_passport;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel password_field;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JLabel welcome_logo;
    // End of variables declaration//GEN-END:variables
}
