/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asset.management;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Christopher Rateng
 */
public class Signup extends javax.swing.JFrame {

   
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtFname = new javax.swing.JTextField();
        TxtLname = new javax.swing.JTextField();
        TxtId = new javax.swing.JTextField();
        TxtTel = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JTextField();
        TxtPassw = new javax.swing.JPasswordField();
        TxtUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnSignup = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        BtnBack = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 30));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telephone :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 30));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Username :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Confirm Password :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 30));
        getContentPane().add(TxtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 30));
        getContentPane().add(TxtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, 30));
        getContentPane().add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, 30));
        getContentPane().add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 30));
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 30));

        TxtPassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 312, 150, 30));
        getContentPane().add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 30));

        BtnSignup.setText("Register New User");
        BtnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        BtnExit.setForeground(new java.awt.Color(255, 0, 0));
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));
        getContentPane().add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 380, -1));

        BtnBack.setForeground(new java.awt.Color(0, 153, 153));
        BtnBack.setText("Return");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/management/screen-4.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // Exits the page
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // Return to home page
        this.setVisible(false);
        new Welcome().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignupActionPerformed
        // ----------------------Check for empty fields--------------------------------------------------------------------------------------------
        if(TxtUsername.getText().trim().isEmpty() && TxtPassword.getText().trim().isEmpty()&& TxtEmail.getText().trim().isEmpty()
                && TxtTel.getText().trim().isEmpty()&& TxtPassw.getText().trim().isEmpty() && TxtId.getText().trim().isEmpty() 
                && TxtFname.getText().trim().isEmpty() && TxtLname.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please fill in your details... !!!");
       }
        
       else if(TxtFname.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "First name Field is Empty !!");
       }
        else if(TxtLname.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Last name Field is Empty !!");
       }
        else if(TxtId.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "ID Field is Empty !!");
       }
         else if(TxtTel.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Telephone Field is Empty !!");
       }
        else if(TxtEmail.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Email Field is Empty !!");
       }
        else if(TxtUsername.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Username Field is Empty !!");
       }
        else if(TxtPassword.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Password Field is Empty !!");
       }
        else if(TxtPassw.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Password Confirmation Field is Empty !!");
       }
        
        //--------------------------Email Validation make sure it is in the correct format-----------------------------------------------------------------------------------
          if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", TxtEmail.getText()))) 
{
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error..!!!", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The email is valid", "OK !!", JOptionPane.INFORMATION_MESSAGE);

            }

          //compare the two password fields are the same
          if (TxtPassword.getText() == TxtPassw.getText()){
              JOptionPane.showMessageDialog(null, "Password match !!");
          }else{
              return;
          }
//---------------Alternative Email validation code
//if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", Txtemail.getText()))) {
            //JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);

            // }
            // else
            // {
              //  JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
            //}
          
          
          //--------------Insert data to the database--------------------------------------------------------------------
       try{
           Class.forName("org.apache.derby.jdbc.ClientDriver");
           java.sql.Connection conn=DriverManager.getConnection("jdbc:derby://localhost:1527/Application","crateng","0000");
           java.sql.Statement st = conn.createStatement();
           
           // mysql insert statement
       String sql="INSERT INTO CRATENG.USERDATA (username, password, email, surname, contacts) "
               + "values ('TxtUsername', 'TxtPassword' , 'TxtEmail', 'TxtSurname', 'TxtContacts')";
       
       ResultSet rs = st.executeQuery(sql);
       PreparedStatement ps;
       
       
        ps = conn.prepareStatement (sql);  
        ps.setString(1,TxtFname.getText());
        ps.setString(1,TxtLname.getText());
        ps.setString(1,TxtId.getText());
        ps.setString(1,TxtTel.getText());
        ps.setString(1,TxtEmail.getText());
        ps.setString(1,TxtUsername.getText());
        ps.setString(1,TxtPassword.getText());
        rs=ps.executeQuery();
        
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Signup Successfully...!");
            } else{
                JOptionPane.showMessageDialog(null, "Login Failed...!!");
            }
       }catch(SQLException ex)
               {
           JOptionPane.showMessageDialog(null, ex);
       } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnSignup;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFname;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtLname;
    private javax.swing.JPasswordField TxtPassw;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
